"""Generate Markdown reports from PackDiagnosis objects."""

from datetime import date

from .diagnose import PackDiagnosis


VERDICT_BADGE = {
    'HEALTHY': 'HEALTHY',
    'DEGRADING': 'DEGRADING',
    'FAILED': 'FAILED',
    'UNKNOWN': 'UNKNOWN',
}


DISCLAIMER_LINES = [
    "> **Important — please read first**",
    ">",
    "> This report was generated by the **pylontech-battery-health** toolkit, an unofficial community tool. It is **not** affiliated with, endorsed by or warranted by Pylontech Technology Co. Ltd or any of its distributors.",
    ">",
    "> The data below was read directly from the battery's own BMS via its native console interface. No values have been altered. The verdict is computed against published cell-imbalance and SOH thresholds.",
    ">",
    "> **The author of this tool accepts zero liability** for any decision, action, warranty outcome or damage arising from use of this report. Treat it as supporting evidence only — Pylontech's own assessment of any returned unit is authoritative.",
]


def _pack_section(diag: PackDiagnosis, heading_level: int = 1) -> list[str]:
    """Render one pack's diagnostic content as Markdown lines.

    heading_level controls the depth of the headings (1 = top-level # for a
    standalone single-pack report; 2 = ## for use as a sub-section within a
    combined rack report).
    """
    h = '#' * heading_level
    badge = VERDICT_BADGE.get(diag.verdict, 'UNKNOWN')

    lines: list[str] = [
        f"{h} Pack {diag.address} — {diag.model or 'Unknown'} — **{badge}**",
        "",
    ]

    if diag.via_master:
        lines += [
            "> **Note:** Queried via the master pack's comm bus. Cell-voltage data, per-cell SOH status and the live `pwr` snapshot are authoritative. Lifetime statistics (`stat`) and the event log (`data event`) are **not captured** in this mode — to retrieve them, plug the cable directly into this pack's console port and re-run the diagnostic.",
            "",
        ]

    lines += [
        f"{h}# Identification",
        "",
        "| | |",
        "|---|---|",
        f"| Model | {diag.model or '--'} |",
        f"| Barcode (serial) | **{diag.barcode or '--'}** |",
        f"| Specification | {diag.spec or '--'} |",
        f"| Release date | {diag.release_date or '--'} |",
        f"| Main software version | {diag.main_soft_version or '--'} |",
        f"| Pack address in rack | {diag.address} |",
        f"| Cell count | {diag.cell_count} |",
        "",
        f"{h}# Verdict reasoning",
        "",
    ]
    if diag.verdict_reasons:
        for r in diag.verdict_reasons:
            lines.append(f"- {r}")
    else:
        lines.append("- All checks passed — no degradation indicators triggered.")

    lines += [
        "",
        f"{h}# Live readings (at time of test)",
        "",
        f"- **Pack voltage:** {diag.pack_voltage_mv / 1000:.2f} V",
        f"- **Pack current:** {diag.pack_current_ma / 1000:.2f} A ({diag.runtime_state})",
        f"- **Pack temperature:** {diag.pack_temp_mc / 1000:.1f} °C",
        f"- **Pack SOC (Coulomb):** {diag.pack_soc_percent} %",
        f"- **Cell-voltage spread:** {diag.spread_mv} mV   *(< 30 mV healthy, 30–50 mV degrading, > 50 mV failed)*",
        f"- **Runtime `Soh. Status` flag:** {diag.runtime_soh_status}",
        "",
        f"{h}# Per-cell readings",
        "",
        "| Cell | Voltage (mV) | Δ from max (mV) | SOC | SOH-abnormal events | SOH status |",
        "|---|---|---|---|---|---|",
    ]
    if diag.cells:
        v_max = max(c.voltage_mv for c in diag.cells)
        for c in diag.cells:
            delta = c.voltage_mv - v_max
            mark = ''
            if c.cell_number in diag.abnormal_cells:
                mark = ' (abnormal)'
            elif diag.weakest_cell == c.cell_number and diag.spread_mv > 30:
                mark = ' (weakest)'
            lines.append(
                f"| {c.cell_number} | {c.voltage_mv}{mark} | {delta} | {c.soc_percent} % | {c.soh_count} | {c.soh_status} |"
            )

    if diag.via_master:
        lines += [
            "",
            f"{h}# Lifetime statistics",
            "",
            "*Not captured in master-relay mode — connect the cable directly to this pack to retrieve full lifetime statistics (BMS-reported SOH, real cycle count, alarm trip counts).*",
            "",
            f"{h}# Most recent stored event",
            "",
            "*Not captured in master-relay mode — connect the cable directly to this pack to retrieve the event log.*",
        ]
    else:
        lines += [
            "",
            f"{h}# Lifetime statistics",
            "",
            "| Metric | Value | Notes |",
            "|---|---|---|",
            f"| BMS-reported SOH | **{'--' if diag.stats.soh_percent is None else f'{diag.stats.soh_percent} %'}** | 0 % = pack declared end-of-life by its own BMS |",
            f"| SOH-abnormal events accumulated | {diag.stats.soh_abnormal_events} | progressive degradation indicator |",
            f"| **Real charge cycles** | **{diag.stats.real_cycles}** | the warranty-relevant cycle metric (`CYCLE Times`) |",
            f"| Charge transitions | {diag.stats.charge_transitions} | NOT real cycles — partial-event counter (`Charge Times`) |",
            f"| Discharge events | {diag.stats.discharge_count} | |",
            f"| Cell over-voltage trips (BOV) | {diag.stats.bat_ov_count} | |",
            f"| Cell high-voltage warnings (BHV) | {diag.stats.bat_hv_count} | |",
            f"| Cell low-voltage warnings (BLV) | {diag.stats.bat_lv_count} | |",
            f"| Cell under-voltage trips (BUV) | {diag.stats.bat_uv_count} | |",
            f"| Charge over-current trips (COC) | {diag.stats.coc_count} | abuse indicator if non-zero |",
            f"| Discharge over-current trips (DOC) | {diag.stats.doc_count} | abuse indicator if non-zero |",
            f"| Short-circuit trips (SC) | {diag.stats.sc_count} | abuse indicator if non-zero |",
            f"| Pack shutdowns | {diag.stats.shut_count} | |",
            f"| BMS resets | {diag.stats.reset_count} | |",
            "",
            f"{h}# Most recent stored event",
            "",
        ]
        header = (diag.most_recent_event or {}).get('header', {}) or {}
        interesting = ['Item Index', 'Time', 'Voltage', 'Current', 'Percent',
                       'Base State', 'Bat Events', 'Power Events', 'System Fault']
        any_event = False
        for k in interesting:
            if k in header:
                lines.append(f"- **{k}:** {header[k]}")
                any_event = True
        if not any_event:
            lines.append("*(No event detail captured — see raw `data event` output below.)*")

    lines += [
        "",
        f"{h}# Raw BMS captures",
        "",
        "Raw command output, suitable for warranty submission as supporting evidence:",
        "",
    ]
    for cmd_label in ('info', 'pwr', 'bat', 'soh', 'stat', 'data_event'):
        if cmd_label in diag.raw:
            lines += [
                f"{h}## `{cmd_label.replace('_', ' ')}`",
                "",
                "```",
                diag.raw[cmd_label].strip(),
                "```",
                "",
            ]
    return lines


def generate_report(diag: PackDiagnosis) -> str:
    """Render a single-pack diagnostic report as Markdown."""
    today = date.today().isoformat()
    badge = VERDICT_BADGE.get(diag.verdict, 'UNKNOWN')

    lines: list[str] = [
        f"# Pylontech {diag.model or 'Battery'} — Diagnostic Report",
        "",
        f"**Report generated:** {today}",
        f"**Verdict:** **{badge}**",
        "",
        "---",
        "",
    ]
    lines.extend(DISCLAIMER_LINES)
    lines += [
        "",
        "---",
        "",
    ]
    lines.extend(_pack_section(diag, heading_level=2))
    lines += [
        "",
        "---",
        "",
        "*Generated by pylontech-battery-health. All BMS counters and statuses are authoritative from the pack's own BMS hardware; no third-party measurement was used.*",
    ]
    return "\n".join(lines)


def generate_rack_report(diagnoses: list[PackDiagnosis], rack_raw: str = "") -> str:
    """Render a single combined Markdown report covering every pack scanned."""
    today = date.today().isoformat()

    # Identify the master / locally connected pack (the one not via_master)
    master = next((d for d in diagnoses if not d.via_master), None)

    # Verdict counts for executive summary
    verdict_counts = {'HEALTHY': 0, 'DEGRADING': 0, 'FAILED': 0, 'UNKNOWN': 0}
    for d in diagnoses:
        verdict_counts[d.verdict] = verdict_counts.get(d.verdict, 0) + 1

    overall = 'HEALTHY'
    if verdict_counts.get('FAILED', 0) > 0:
        overall = 'FAILED'
    elif verdict_counts.get('DEGRADING', 0) > 0:
        overall = 'DEGRADING'

    lines: list[str] = [
        "# Pylontech Rack — Whole-Rack Diagnostic Report",
        "",
        f"**Report generated:** {today}",
        f"**Overall rack verdict:** **{overall}**",
        f"**Packs scanned:** {len(diagnoses)} "
        f"(Healthy: {verdict_counts.get('HEALTHY', 0)}, "
        f"Degrading: {verdict_counts.get('DEGRADING', 0)}, "
        f"Failed: {verdict_counts.get('FAILED', 0)})",
        "",
    ]
    if master:
        lines.append(
            f"**Connected to:** Pack {master.address} — {master.model or '--'} "
            f"(barcode `{master.barcode or '--'}`)"
        )
        lines.append("")

    lines += [
        "---",
        "",
    ]
    lines.extend(DISCLAIMER_LINES)
    lines += [
        "",
        "---",
        "",
        "## Verdict summary",
        "",
        "| Pack | Model | Barcode | Verdict | Spread (mV) | Connected | Weakest cell |",
        "|---|---|---|---|---|---|---|",
    ]
    for d in diagnoses:
        connect_mode = 'direct' if not d.via_master else 'via master'
        weakest = f"cell {d.weakest_cell}" if d.weakest_cell is not None else '--'
        lines.append(
            f"| **{d.address}** | {d.model or '--'} | `{d.barcode or '--'}` | "
            f"**{VERDICT_BADGE.get(d.verdict, 'UNKNOWN')}** | "
            f"{d.spread_mv} | {connect_mode} | {weakest} |"
        )

    lines += [
        "",
        "## Verdict thresholds (legend)",
        "",
        "- 🟢 **HEALTHY** — cell-voltage spread < 30 mV under load, no flagged cells, BMS reports normal SOH",
        "- 🟡 **DEGRADING** — spread 30–50 mV, OR one or more flagged cells, OR sustained SOH-abnormal events",
        "- 🔴 **FAILED** — spread > 50 mV, OR BMS-reported SOH = 0, OR runtime `Soh. Status` flag is `Abnormal`",
        "",
        "## Recommended next steps",
        "",
    ]
    failed_or_degrading = [d for d in diagnoses if d.verdict in ('FAILED', 'DEGRADING')]
    if not failed_or_degrading:
        lines.append("- **No action required.** All packs scanned reported HEALTHY.")
    else:
        lines.append("- For each pack flagged as **FAILED** or **DEGRADING** below, **plug the cable directly into that pack's console port** and re-run the diagnostic. This captures the per-pack lifetime statistics, per-cell SOH counters and full event log that the master-bus relay does not propagate — they are essential evidence for warranty / RMA discussions.")
        lines.append("- Inspect each failed/degrading pack physically for any swelling, blue residue at ports, terminal corrosion or thermal damage.")
        lines.append("- If multiple packs from the same manufacturing batch (sequential serial numbers, same release date) are failing, note this pattern when raising your service request — it may indicate a cell-batch defect rather than independent end-of-life.")

    lines += [
        "",
        "---",
        "",
        "## Per-pack details",
        "",
    ]
    for d in diagnoses:
        lines.extend(_pack_section(d, heading_level=3))
        lines.append("")
        lines.append("---")
        lines.append("")

    if rack_raw.strip():
        lines += [
            "## Raw rack `pwr` table (whole-rack snapshot at time of scan)",
            "",
            "```",
            rack_raw.strip(),
            "```",
            "",
        ]

    lines += [
        "*Generated by pylontech-battery-health. All BMS counters and statuses are authoritative from the packs' own BMS hardware; no third-party measurement was used.*",
    ]
    return "\n".join(lines)
